export const CHAT_PROMPT_SERVICE = Symbol('CHAT_PROMPT_SERVICE');
export const CHAT_PROMPT_WITH_TOOL_SERVICE = Symbol('CHAT_PROMPT_WITH_TOOL_SERVICE');
export const CHAT_VISION_PROMPT_SERVICE = Symbol('CHAT_VISION_PROMPT_SERVICE');